/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'fdearle' at '19/04/16 09:30' with Gradle 2.12
 *
 * @author fdearle, @date 19/04/16 09:30
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
